set_property PACKAGE_PIN W4 [get_ports txp]
set_property PACKAGE_PIN AA18 [get_ports tx_disable]
set_property IOSTANDARD LVCMOS25 [get_ports tx_disable]
set_property PACKAGE_PIN AC8 [get_ports refclk_p]


set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[6]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TUSER[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TLAST[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[6]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TLAST[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDEST[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TID[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[6]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TSTRB[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TID[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDEST[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[1]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[2]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[3]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[5]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[6]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TSTRB[4]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TUSER[0]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/out_intf_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {blockdes_fixed_i/top_0/in_intf_TDATA[6]}]
set_property MARK_DEBUG true [get_nets blockdes_fixed_i/top_0/in_intf_TREADY]
set_property MARK_DEBUG true [get_nets blockdes_fixed_i/top_0/out_intf_TVALID]
set_property MARK_DEBUG true [get_nets blockdes_fixed_i/top_0/out_intf_TREADY]
set_property MARK_DEBUG true [get_nets blockdes_fixed_i/top_0/in_intf_TVALID]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list blockdes_fixed_i/axi_10g_ethernet_0/inst/ten_gig_eth_pcs_pma/inst/ten_gig_eth_pcs_pma_shared_clock_reset_block/coreclk_out]]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {blockdes_fixed_i/top_0/in_intf_TDATA[0]} {blockdes_fixed_i/top_0/in_intf_TDATA[1]} {blockdes_fixed_i/top_0/in_intf_TDATA[2]} {blockdes_fixed_i/top_0/in_intf_TDATA[3]} {blockdes_fixed_i/top_0/in_intf_TDATA[4]} {blockdes_fixed_i/top_0/in_intf_TDATA[5]} {blockdes_fixed_i/top_0/in_intf_TDATA[6]} {blockdes_fixed_i/top_0/in_intf_TDATA[7]} {blockdes_fixed_i/top_0/in_intf_TDATA[8]} {blockdes_fixed_i/top_0/in_intf_TDATA[9]} {blockdes_fixed_i/top_0/in_intf_TDATA[10]} {blockdes_fixed_i/top_0/in_intf_TDATA[11]} {blockdes_fixed_i/top_0/in_intf_TDATA[12]} {blockdes_fixed_i/top_0/in_intf_TDATA[13]} {blockdes_fixed_i/top_0/in_intf_TDATA[14]} {blockdes_fixed_i/top_0/in_intf_TDATA[15]} {blockdes_fixed_i/top_0/in_intf_TDATA[16]} {blockdes_fixed_i/top_0/in_intf_TDATA[17]} {blockdes_fixed_i/top_0/in_intf_TDATA[18]} {blockdes_fixed_i/top_0/in_intf_TDATA[19]} {blockdes_fixed_i/top_0/in_intf_TDATA[20]} {blockdes_fixed_i/top_0/in_intf_TDATA[21]} {blockdes_fixed_i/top_0/in_intf_TDATA[22]} {blockdes_fixed_i/top_0/in_intf_TDATA[23]} {blockdes_fixed_i/top_0/in_intf_TDATA[24]} {blockdes_fixed_i/top_0/in_intf_TDATA[25]} {blockdes_fixed_i/top_0/in_intf_TDATA[26]} {blockdes_fixed_i/top_0/in_intf_TDATA[27]} {blockdes_fixed_i/top_0/in_intf_TDATA[28]} {blockdes_fixed_i/top_0/in_intf_TDATA[29]} {blockdes_fixed_i/top_0/in_intf_TDATA[30]} {blockdes_fixed_i/top_0/in_intf_TDATA[31]} {blockdes_fixed_i/top_0/in_intf_TDATA[32]} {blockdes_fixed_i/top_0/in_intf_TDATA[33]} {blockdes_fixed_i/top_0/in_intf_TDATA[34]} {blockdes_fixed_i/top_0/in_intf_TDATA[35]} {blockdes_fixed_i/top_0/in_intf_TDATA[36]} {blockdes_fixed_i/top_0/in_intf_TDATA[37]} {blockdes_fixed_i/top_0/in_intf_TDATA[38]} {blockdes_fixed_i/top_0/in_intf_TDATA[39]} {blockdes_fixed_i/top_0/in_intf_TDATA[40]} {blockdes_fixed_i/top_0/in_intf_TDATA[41]} {blockdes_fixed_i/top_0/in_intf_TDATA[42]} {blockdes_fixed_i/top_0/in_intf_TDATA[43]} {blockdes_fixed_i/top_0/in_intf_TDATA[44]} {blockdes_fixed_i/top_0/in_intf_TDATA[45]} {blockdes_fixed_i/top_0/in_intf_TDATA[46]} {blockdes_fixed_i/top_0/in_intf_TDATA[47]} {blockdes_fixed_i/top_0/in_intf_TDATA[48]} {blockdes_fixed_i/top_0/in_intf_TDATA[49]} {blockdes_fixed_i/top_0/in_intf_TDATA[50]} {blockdes_fixed_i/top_0/in_intf_TDATA[51]} {blockdes_fixed_i/top_0/in_intf_TDATA[52]} {blockdes_fixed_i/top_0/in_intf_TDATA[53]} {blockdes_fixed_i/top_0/in_intf_TDATA[54]} {blockdes_fixed_i/top_0/in_intf_TDATA[55]} {blockdes_fixed_i/top_0/in_intf_TDATA[56]} {blockdes_fixed_i/top_0/in_intf_TDATA[57]} {blockdes_fixed_i/top_0/in_intf_TDATA[58]} {blockdes_fixed_i/top_0/in_intf_TDATA[59]} {blockdes_fixed_i/top_0/in_intf_TDATA[60]} {blockdes_fixed_i/top_0/in_intf_TDATA[61]} {blockdes_fixed_i/top_0/in_intf_TDATA[62]} {blockdes_fixed_i/top_0/in_intf_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TDATA[0]} {blockdes_fixed_i/top_0/out_intf_TDATA[1]} {blockdes_fixed_i/top_0/out_intf_TDATA[2]} {blockdes_fixed_i/top_0/out_intf_TDATA[3]} {blockdes_fixed_i/top_0/out_intf_TDATA[4]} {blockdes_fixed_i/top_0/out_intf_TDATA[5]} {blockdes_fixed_i/top_0/out_intf_TDATA[6]} {blockdes_fixed_i/top_0/out_intf_TDATA[7]} {blockdes_fixed_i/top_0/out_intf_TDATA[8]} {blockdes_fixed_i/top_0/out_intf_TDATA[9]} {blockdes_fixed_i/top_0/out_intf_TDATA[10]} {blockdes_fixed_i/top_0/out_intf_TDATA[11]} {blockdes_fixed_i/top_0/out_intf_TDATA[12]} {blockdes_fixed_i/top_0/out_intf_TDATA[13]} {blockdes_fixed_i/top_0/out_intf_TDATA[14]} {blockdes_fixed_i/top_0/out_intf_TDATA[15]} {blockdes_fixed_i/top_0/out_intf_TDATA[16]} {blockdes_fixed_i/top_0/out_intf_TDATA[17]} {blockdes_fixed_i/top_0/out_intf_TDATA[18]} {blockdes_fixed_i/top_0/out_intf_TDATA[19]} {blockdes_fixed_i/top_0/out_intf_TDATA[20]} {blockdes_fixed_i/top_0/out_intf_TDATA[21]} {blockdes_fixed_i/top_0/out_intf_TDATA[22]} {blockdes_fixed_i/top_0/out_intf_TDATA[23]} {blockdes_fixed_i/top_0/out_intf_TDATA[24]} {blockdes_fixed_i/top_0/out_intf_TDATA[25]} {blockdes_fixed_i/top_0/out_intf_TDATA[26]} {blockdes_fixed_i/top_0/out_intf_TDATA[27]} {blockdes_fixed_i/top_0/out_intf_TDATA[28]} {blockdes_fixed_i/top_0/out_intf_TDATA[29]} {blockdes_fixed_i/top_0/out_intf_TDATA[30]} {blockdes_fixed_i/top_0/out_intf_TDATA[31]} {blockdes_fixed_i/top_0/out_intf_TDATA[32]} {blockdes_fixed_i/top_0/out_intf_TDATA[33]} {blockdes_fixed_i/top_0/out_intf_TDATA[34]} {blockdes_fixed_i/top_0/out_intf_TDATA[35]} {blockdes_fixed_i/top_0/out_intf_TDATA[36]} {blockdes_fixed_i/top_0/out_intf_TDATA[37]} {blockdes_fixed_i/top_0/out_intf_TDATA[38]} {blockdes_fixed_i/top_0/out_intf_TDATA[39]} {blockdes_fixed_i/top_0/out_intf_TDATA[40]} {blockdes_fixed_i/top_0/out_intf_TDATA[41]} {blockdes_fixed_i/top_0/out_intf_TDATA[42]} {blockdes_fixed_i/top_0/out_intf_TDATA[43]} {blockdes_fixed_i/top_0/out_intf_TDATA[44]} {blockdes_fixed_i/top_0/out_intf_TDATA[45]} {blockdes_fixed_i/top_0/out_intf_TDATA[46]} {blockdes_fixed_i/top_0/out_intf_TDATA[47]} {blockdes_fixed_i/top_0/out_intf_TDATA[48]} {blockdes_fixed_i/top_0/out_intf_TDATA[49]} {blockdes_fixed_i/top_0/out_intf_TDATA[50]} {blockdes_fixed_i/top_0/out_intf_TDATA[51]} {blockdes_fixed_i/top_0/out_intf_TDATA[52]} {blockdes_fixed_i/top_0/out_intf_TDATA[53]} {blockdes_fixed_i/top_0/out_intf_TDATA[54]} {blockdes_fixed_i/top_0/out_intf_TDATA[55]} {blockdes_fixed_i/top_0/out_intf_TDATA[56]} {blockdes_fixed_i/top_0/out_intf_TDATA[57]} {blockdes_fixed_i/top_0/out_intf_TDATA[58]} {blockdes_fixed_i/top_0/out_intf_TDATA[59]} {blockdes_fixed_i/top_0/out_intf_TDATA[60]} {blockdes_fixed_i/top_0/out_intf_TDATA[61]} {blockdes_fixed_i/top_0/out_intf_TDATA[62]} {blockdes_fixed_i/top_0/out_intf_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TSTRB[0]} {blockdes_fixed_i/top_0/out_intf_TSTRB[1]} {blockdes_fixed_i/top_0/out_intf_TSTRB[2]} {blockdes_fixed_i/top_0/out_intf_TSTRB[3]} {blockdes_fixed_i/top_0/out_intf_TSTRB[4]} {blockdes_fixed_i/top_0/out_intf_TSTRB[5]} {blockdes_fixed_i/top_0/out_intf_TSTRB[6]} {blockdes_fixed_i/top_0/out_intf_TSTRB[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {blockdes_fixed_i/top_0/in_intf_TLAST[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TID[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {blockdes_fixed_i/top_0/in_intf_TUSER[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TKEEP[0]} {blockdes_fixed_i/top_0/out_intf_TKEEP[1]} {blockdes_fixed_i/top_0/out_intf_TKEEP[2]} {blockdes_fixed_i/top_0/out_intf_TKEEP[3]} {blockdes_fixed_i/top_0/out_intf_TKEEP[4]} {blockdes_fixed_i/top_0/out_intf_TKEEP[5]} {blockdes_fixed_i/top_0/out_intf_TKEEP[6]} {blockdes_fixed_i/top_0/out_intf_TKEEP[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TUSER[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {blockdes_fixed_i/top_0/in_intf_TKEEP[0]} {blockdes_fixed_i/top_0/in_intf_TKEEP[1]} {blockdes_fixed_i/top_0/in_intf_TKEEP[2]} {blockdes_fixed_i/top_0/in_intf_TKEEP[3]} {blockdes_fixed_i/top_0/in_intf_TKEEP[4]} {blockdes_fixed_i/top_0/in_intf_TKEEP[5]} {blockdes_fixed_i/top_0/in_intf_TKEEP[6]} {blockdes_fixed_i/top_0/in_intf_TKEEP[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TLAST[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {blockdes_fixed_i/top_0/out_intf_TDEST[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list blockdes_fixed_i/top_0/in_intf_TREADY]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list blockdes_fixed_i/top_0/in_intf_TVALID]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list blockdes_fixed_i/top_0/out_intf_TREADY]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list blockdes_fixed_i/top_0/out_intf_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_coreclk_out]
